#file: noinspection SpringBootApplicationYaml
server:
  port: 10101
spring:
  application:
    name: payment
  config:
    activate:
      on-profile: local
  cache:
    redis:
      time-to-live: 60000
      key-prefix: payment
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: localhost
      port: 6379
  threads:
    virtual:
      enabled: true
r2dbc:
  master:
    url: r2dbc:pool:postgresql://localhost:5432/payment
    username: postgres
    password: postgres
  slave:
    url: r2dbc:pool:postgresql://localhost:5433/payment
    username: postgres
    password: postgres

axon:
  serializer:
    general: xstream
  axonserver:
    servers: localhost:8124
jasypt:
  encryptor:
    bean: jasyptStringEncryptor