server:
  port: 10101
spring:
  application:
    name: payment
  threads:
    virtual:
      enabled: true
r2dbc:
  master:
    url: r2dbc:pool:postgresql://host.docker.internal:5432/cherhy
    username: postgres
    password: 1234
  slave:
    url: r2dbc:pool:postgresql://host.docker.internal:5432/cherhy
    username: postgres
    password: 1234

axon:
  serializer:
    general: xstream
  axonserver:
    servers: host.docker.internal:8124
jasypt:
  encryptor:
    bean: jasyptStringEncryptor