#file: noinspection SpringBootApplicationYaml
server:
  port: 10101
spring:
  application:
    name: payment
  config:
    activate:
      on-profile: dev
  cache:
    redis:
      time-to-live: 60000
      key-prefix: payment
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: host.docker.internal
      port: 6379
  threads:
    virtual:
      enabled: true
r2dbc:
  master:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://host.docker.internal:5432/payment
    username: postgres
    password: postgres
  slave:
    driver-class-name: org.postgresql.Driver
    url: r2dbc:postgresql://host.docker.internal:5433/payment
    username: postgres
    password: postgres

axon:
  serializer:
    general: xstream
  axonserver:
    servers: host.docker.internal:8124
jasypt:
  encryptor:
    bean: jasyptStringEncryptor